export interface Buff {
  id: string;
  name: string;
  failThreshold?: number;
  passThreshold?: number;
  imageData: string;
  scaledImageData?: string;
  desaturatedImageData: string;
  scaledDesaturatedImageData?: string;
  defaultImageData?: string;
  duration?: number;
  cooldown?: number;
  cooldownRemaining?: number;
  timeRemaining?: number;
  isPermanent?: boolean;
  hasAlert?: boolean;
  hasAlerted?: boolean;
  alertThreshold?: number;
  buffType?: string;
  isActive: boolean;
  alwaysActive?: boolean;
  lastUpdated?: number;
  inactiveCount?: number;
  isUtility?: boolean;
  childBuffNames?: string[];
  isStack?: boolean;
  noNumberDisplay?: boolean;
  categories?: string[];
}